// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFFYug3EOkrY-rVWZulhMM2RGe04oSYIQ',
    appId: '1:1081744772253:web:d09f494230429ba362d874',
    messagingSenderId: '1081744772253',
    projectId: 'air-esp32',
    authDomain: 'air-esp32.firebaseapp.com',
    databaseURL: 'https://air-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'air-esp32.firebasestorage.app',
    measurementId: 'G-BQVXXDGZFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCwUjU1mi24MON68nrLPQCrL-hrLa-X7E',
    appId: '1:1081744772253:android:75df7f4d3b2db32a62d874',
    messagingSenderId: '1081744772253',
    projectId: 'air-esp32',
    databaseURL: 'https://air-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'air-esp32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJuVEyjQfvd8GaHCNkP8wDTM1C7s1Cw8I',
    appId: '1:1081744772253:ios:9f816868cefe249e62d874',
    messagingSenderId: '1081744772253',
    projectId: 'air-esp32',
    databaseURL: 'https://air-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'air-esp32.firebasestorage.app',
    iosBundleId: 'com.example.air',
  );
}
